[tool.poetry]
name = "package-comparison-module"
version = "0.1.0"
description = ""
authors = ["igorkonov <igorkonov1993@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
